spring:
  application:
    name: CONFIGPROD
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
  service-url:
    defaultZone: http://localhost:8761/eureka/
